server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
         - id: api_route
           uri: http://localhost:8123
           predicates:
             - Path=/api/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: warn

dubbo:
  application:
    name: com.vkls.project-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848